# Generated by Django 4.1.2 on 2022-11-03 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_schedule',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 19, 55, 58, 742477)),
        ),
        migrations.AlterField(
            model_name='quiz_response',
            name='answer_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_response',
            name='correct_answer_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_response',
            name='question_tags',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_response',
            name='question_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_response',
            name='quiz_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_response',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_response',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_response',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
